# Generated by Django 6.1.1 on 2026-09-30 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_install_fts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='Draft awaiting review by an admin.'),
        ),
        migrations.AddField(
            model_name='revision',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revision',
            name='proposed_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories requested by a pending edit.', related_name='pending_revisions', to='articles.category'),
        ),
        migrations.AddField(
            model_name='revision',
            name='proposed_summary',
            field=models.CharField(blank=True, help_text='Summary requested by a pending edit.', max_length=500),
        ),
        migrations.AddField(
            model_name='revision',
            name='proposed_title',
            field=models.CharField(blank=True, help_text='Title requested by a pending edit.', max_length=255),
        ),
        migrations.AddField(
            model_name='revision',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revision',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
